title:       "Operating Systems 2021-1 (OS211)"
version:     "0031a---07-Mar-2021"
copyright:   "2021-2021"
google_analytics: ""
author:           "Fayaad"
address:          "Jakarta"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://fayaadbsa.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/fayaadbsa/os211/"
urlghpage:        "https://fayaadbsa.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]
