title:       "Operating Systems 2021-1 (OS211)"
copyright:   "2021-2021"

author:           "Fayaad"
address:          "Jakarta"
sitemap:          "true"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://fayaadbsa.github.io/os211/"
urlgithub:        "https://github.com/fayaadbsa/os211/"
urlghpage:        "https://fayaadbsa.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]
